/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Joleen Schwellenbach
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public Registration() {
        initComponents();
        this.setTitle("Pet Registration");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.getRootPane().setDefaultButton(submitButton);
        this.setVisible(true);
        this.pack();
    }
    
    public void displayMessage(String message, String title){
        JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE);
    }
    
    public void addMyListener(ActionListener listen){
        submitButton.addActionListener(listen);
        resetButton.addActionListener(listen);
    }
    
    //Getters
    public JButton getSubmitButton() {
        return submitButton;
    }
    
    public JButton getResetButton() {
        return resetButton;
    }
    
    public JRadioButton getFemaleRadioButton() {
        return femaleRadioButton;
    }

    public JRadioButton getMaleRadioButton() {
        return maleRadioButton;
    }
    
    public JTextField getBreedTextField() {
        return breedTextField;
    }

    public JTextField getPetNameTextField() {
        return petNameTextField;
    }
    
    public JTextField getCusNameTextField() {
        return cusNameTextField;
    }
    
    public JTextField getPhoneTextField() {
        return phoneTextField;
    }

    public String getBreedText() {
        return breedTextField.getText();
    }

    public String getPetNameText() {
        return petNameTextField.getText();
    } 
    
    public String getCusNameText() {
        return cusNameTextField.getText();
    }
    
    public String getPhoneText() {
        return phoneTextField.getText();
    }
    
    public String getPhoneType() {
        return phoneTypeComboBox.getSelectedItem().toString();
    }
    
    public String getMonth() {
        return monthComboBox.getSelectedItem().toString();
    }
    
    public int getYear() {
        return (int)yearComboBox.getSelectedItem();
    }
    
    public int getMonthNumber(){
        return monthComboBox.getSelectedIndex() + 1;
    }
    
    
    //Setters
    public void setBreedText(String breed) {
        this.breedTextField.setText(breed);
    }

    public void setPetNameText(String name) {
        this.petNameTextField.setText(name);
    }
    
    public void setCusNameText(String name) {
        this.cusNameTextField.setText(name);
    }
    
    public void setPhoneText(String phone) {
        this.phoneTextField.setText(phone);
    }

    public void setMessage(String message) {
        this.messageTextArea.setText(message);
    }

    public void setMonthItem(String item) {
        this.monthComboBox.addItem(item);
    }
    
    public void setPhoneTypeItem(String item) {
        this.phoneTypeComboBox.addItem(item);
    }
    
    public void setYearItem(int item) {
        this.yearComboBox.addItem(item);
    }
        
    public void setPhoneType(int index){
        this.phoneTypeComboBox.setSelectedIndex(index);
    }
    
    public void setYear(int index){
        this.yearComboBox.setSelectedIndex(index);
    }
    
    public void setMonth(int index){
        this.monthComboBox.setSelectedIndex(index);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        petPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        petNameTextField = new javax.swing.JTextField();
        breedLabel = new javax.swing.JLabel();
        breedTextField = new javax.swing.JTextField();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();
        genderLabel = new javax.swing.JLabel();
        kennelCoughPanel = new javax.swing.JPanel();
        monthLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        monthComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new javax.swing.JComboBox<>();
        messagePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        customerPanel = new javax.swing.JPanel();
        cusNameLabel = new javax.swing.JLabel();
        cusNameTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneTypeLabel = new javax.swing.JLabel();
        phoneTypeComboBox = new javax.swing.JComboBox<>();
        phoneTextField = new javax.swing.JFormattedTextField();
        resetButton = new javax.swing.JButton();
        petRegLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        petPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pet Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        petPanel.setPreferredSize(new java.awt.Dimension(234, 264));

        nameLabel.setText("Name:");

        breedLabel.setText("Breed:");

        genderButtonGroup.add(maleRadioButton);
        maleRadioButton.setSelected(true);
        maleRadioButton.setText("Male");

        genderButtonGroup.add(femaleRadioButton);
        femaleRadioButton.setText("Female");

        submitButton.setText("Submit");

        genderLabel.setText("Gender:");

        kennelCoughPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Last Kennel Cough", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        monthLabel.setText("Month:");
        monthLabel.setName(""); // NOI18N

        yearLabel.setText("Year:");

        javax.swing.GroupLayout kennelCoughPanelLayout = new javax.swing.GroupLayout(kennelCoughPanel);
        kennelCoughPanel.setLayout(kennelCoughPanelLayout);
        kennelCoughPanelLayout.setHorizontalGroup(
            kennelCoughPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kennelCoughPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kennelCoughPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthComboBox, 0, 264, Short.MAX_VALUE)
                    .addComponent(yearComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kennelCoughPanelLayout.createSequentialGroup()
                        .addGroup(kennelCoughPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monthLabel)
                            .addComponent(yearLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        kennelCoughPanelLayout.setVerticalGroup(
            kennelCoughPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kennelCoughPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(monthLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yearLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout petPanelLayout = new javax.swing.GroupLayout(petPanel);
        petPanel.setLayout(petPanelLayout);
        petPanelLayout.setHorizontalGroup(
            petPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(petPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(petPanelLayout.createSequentialGroup()
                        .addComponent(maleRadioButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, petPanelLayout.createSequentialGroup()
                        .addGroup(petPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submitButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kennelCoughPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, petPanelLayout.createSequentialGroup()
                                .addGroup(petPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel)
                                    .addComponent(breedLabel)
                                    .addComponent(femaleRadioButton)
                                    .addComponent(genderLabel))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(petNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(breedTextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
        );
        petPanelLayout.setVerticalGroup(
            petPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(petNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(breedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(breedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maleRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(femaleRadioButton)
                .addGap(18, 18, 18)
                .addComponent(kennelCoughPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        messagePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pets Registered", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        messageTextArea.setEditable(false);
        messageTextArea.setColumns(20);
        messageTextArea.setLineWrap(true);
        messageTextArea.setRows(5);
        messageTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(messageTextArea);

        javax.swing.GroupLayout messagePanelLayout = new javax.swing.GroupLayout(messagePanel);
        messagePanel.setLayout(messagePanelLayout);
        messagePanelLayout.setHorizontalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );
        messagePanelLayout.setVerticalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        customerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        customerPanel.setPreferredSize(new java.awt.Dimension(234, 264));

        cusNameLabel.setText("Name:");

        phoneLabel.setText("Phone:");

        phoneTypeLabel.setText("Phone Type:");

        try {
            phoneTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cusNameTextField)
                    .addComponent(phoneTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cusNameLabel)
                            .addComponent(phoneLabel)
                            .addComponent(phoneTypeLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(phoneTextField))
                .addContainerGap())
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cusNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cusNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(phoneTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        resetButton.setText("Clear Form for New Customer/Pet");

        petRegLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        petRegLabel.setText("Pet Registration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(petPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(petRegLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(petRegLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(petPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(resetButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(messagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel breedLabel;
    private javax.swing.JTextField breedTextField;
    private javax.swing.JLabel cusNameLabel;
    private javax.swing.JTextField cusNameTextField;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel kennelCoughPanel;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField petNameTextField;
    private javax.swing.JPanel petPanel;
    private javax.swing.JLabel petRegLabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JFormattedTextField phoneTextField;
    private javax.swing.JComboBox<String> phoneTypeComboBox;
    private javax.swing.JLabel phoneTypeLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JComboBox<Integer> yearComboBox;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
